name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, pdo_mysql
    - name: Copy .env
      run: copy .env.example .env
    - name: Set Database Config
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=db4free.net" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=mzalendo" >> .env
        echo "DB_USERNAME=mzalendo" >> .env
        echo "DB_PASSWORD=Messigoat@2021" >> .env
    - name: Install Dependencies
      run: composer install --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: Generate Application Key
      run: php artisan key:generate
    - name: Directory Permissions
      run: icacls "storage" /grant:r "IIS_IUSRS:(OI)(CI)F" /T
    - name: Create Database
      run: |
        php artisan config:cache
        php artisan migrate --force
    - name: Test Database Connection
      run: php artisan test-database-connection
    - name: Execute PHPUnit Tests
      run: vendor\bin\phpunit
